import { DecisionBadge } from "./DecisionBadge";
import { Panel } from "./ui";
import type { FinalBehavior, ToolResult } from "@/lib/schemas";

export function FinalBehaviorPanel({
  final,
  toolResults,
}: {
  final: FinalBehavior;
  toolResults: ToolResult[];
}) {
  return (
    <Panel
      eyebrow="Step 4"
      title="System response"
      className="h-full"
      aside={<DecisionBadge behavior={final.behavior} />}
    >
      <div className="text-[13px] font-medium text-ink">{final.headline}</div>

      {final.behavior === "VERIFY" && (
        <p className="mt-2 text-[12px] text-muted">
          Evidence required before action. The verification steps below ran against synthetic
          systems of record.
        </p>
      )}

      <p className="mt-2 whitespace-pre-line text-[13.5px] leading-relaxed text-ink">
        {final.body}
      </p>

      {final.behavior === "VERIFY" && toolResults.length > 0 && (
        <ol className="mt-3 space-y-1.5 border-l-2 border-warn/50 pl-3">
          {toolResults.map((r) => (
            <li key={r.call_id} className="text-[12.5px] leading-relaxed text-ink-soft">
              <span className="font-mono text-[11px] uppercase tracking-wider text-muted">
                {r.status}
              </span>{" "}
              {r.summary}
            </li>
          ))}
        </ol>
      )}

      {final.bullets.length > 0 && final.behavior !== "VERIFY" && final.behavior !== "ANSWER" && (
        <ul className="mt-3 space-y-1.5 border-t border-line pt-3">
          {final.bullets.map((b, i) => (
            <li key={i} className="text-[12.5px] leading-relaxed text-ink-soft">
              · {b}
            </li>
          ))}
        </ul>
      )}

      {final.behavior === "ANSWER" && (
        <div className="mt-3 border-t border-line pt-3">
          <div className="eyebrow">Grounded in</div>
          {final.grounded_in.length > 0 ? (
            <ul className="mt-1.5 space-y-1">
              {final.grounded_in.map((g, i) => (
                <li key={i} className="text-[11.5px] leading-relaxed text-muted">
                  · {g}
                </li>
              ))}
            </ul>
          ) : (
            <p className="mt-1 text-[11.5px] text-muted">
              Nothing was retrieved: this answer rests on the request itself and general knowledge.
            </p>
          )}
        </div>
      )}

      <div className="mt-3 border-t border-line pt-2 text-[11px] text-muted">
        Text generated by {final.generator === "model" ? "the model" : "a deterministic template"}.
      </div>
    </Panel>
  );
}
